[package]
name = "shareverse-twitter-bot"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ethers = "2.0"
serde = { version="1.0.164", features=["derive"] }
tokio = { version = "1", features = ["full"] }
