[package]
name = "shareverse-twitter-bot"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.26"
dotenv = "0.15.0"
ethers = "2.0"
eyre = "0.6.8"
log = "0.4.19"
reqwest = { version = "0.11", features = ["json", "cookies"] }
serde = { version="1.0.164", features=["derive"] }
serde_json = "1.0.100"
tokio = { version = "1", features = ["full"] }
