/// Generated by https://quicktype.io
extern crate serde_json;
use serde::{Deserialize, Serialize};

use super::search::{AdvertiserResultsResult, FluffyLegacy, Views};

#[derive(Serialize, Deserialize, Debug)]
pub struct TweetsAnalysis {
    pub views: Views,
    pub legacy: FluffyLegacy,
    pub user_result: AdvertiserResultsResult,
}
